### ISSUE TITLE
Create extension point to allow contributing 3rd-party/external project templates.

### ISSUE THREAD

**Issue by jbadeau** [SOM-Research/asyncapi-toolkit#3]
Hello,

I would like to supply my own generator templates. Are there any docs or links on this?

**Comment by abelgomez** [comment]
Hi @jbadeau ,

I haven't written documentation on this, but if you have experience with Eclipse and extension points (which is a requirement), you should be able to do it by inspecting the `io.github.abelgomez.asyncapi.i40.ui` plug-in.

This project contributes two additional project templates as if they were "external":
* _AsyncAPI Project from I4.0 UML Model_
* _Example AsyncAPI Project from I4.0 UML model_

The process is simple:
1. Create a new project template by extending the class [`io.github.abelgomez.asyncapi.ui.wizard.AbstractAsyncApiProjectTemplate.xtend`](https://github.com/SOM-Research/asyncapi-toolkit/blob/master/plugins/io.github.abelgomez.asyncapi.ui/src/io/github/abelgomez/asyncapi/ui/wizard/AbstractAsyncApiProjectTemplate.xtend). You can see two examples in [`plugins/io.github.abelgomez.asyncapi.i40.ui/src/io/github/abelgomez/asyncapi/i40/ui/wizard`](https://github.com/SOM-Research/asyncapi-toolkit/tree/master/plugins/io.github.abelgomez.asyncapi.i40.ui/src/io/github/abelgomez/asyncapi/i40/ui/wizard). Notice that I used Xtend to implement the classes, but you can use plain Java.
2. In your new project template, you should generate the files of your new kind of project with the contents that you wish inside the `createProjectFactory` method. 
3. Make use of the `io.github.abelgomez.asyncapi.ui.projectTemplate` extension point in your `plugin.xml`. You only need to put the FQN of your newly implemented classes. You can see [`plugins/io.github.abelgomez.asyncapi.i40.ui/plugin.xml`](https://github.com/SOM-Research/asyncapi-toolkit/blob/master/plugins/io.github.abelgomez.asyncapi.i40.ui/plugin.xml ) for an example.

Keep one thing in mind: since we are generating Java code in all our wizards, the `AbstractAsyncApiProjectTemplate` class always generates the minimal infrastructure all Java projects share. Sorry if that's not what you need. I didn't think on generating plain empty projects (but it could be easily done if needed).

That's all. As I said, it's not difficult, but of course you need to know how to implement Eclipse plug-ins :)

**Comment by abelgomez** [comment]
BTW, one clarification: project templates are aimed to create the initial contents of a project (i.e., the AsyncAPI file, example files, models, manifests, etc., possibly from another kind of artifact). But once the project has been created, the generation phase is always the same: Java code is generated out of the AsyncAPI specification.

Providing a different generation template (e.g., to generate Python code from the AsyncAPI specification) is not possible using a extension point since at this point does not make sense: a new generation template would imply almost a complete re-implementation of the _AsyncAPI Toolkit_ funtionality.

Nevertheless, you can make use of the provided metamodel (see [`plugins/io.github.abelgomez.asyncapi/model/generated/AsyncApi.ecore`](https://github.com/SOM-Research/asyncapi-toolkit/blob/master/plugins/io.github.abelgomez.asyncapi/model/generated/AsyncApi.ecore) and [`plugins/io.github.abelgomez.asyncapi/src-gen/io/github/abelgomez/asyncapi/asyncApi`](https://github.com/SOM-Research/asyncapi-toolkit/tree/master/plugins/io.github.abelgomez.asyncapi/src-gen/io/github/abelgomez/asyncapi/asyncApi)) to implement your own _AsyncAPI to whatever_ model transformation in your own plug-in.

**Comment by abelgomez** [comment]
Closing this issue, since this request, supposing it is requesting what I explain in https://github.com/SOM-Research/asyncapi-toolkit/issues/3#issuecomment-1122218841, is out of the scope of the project goals (at least in the short/medium term)

**Comment by abelgomez** [comment]
If I misunderstood your request, feel free to reopen the issue with more information.
