### ISSUE TITLE
The selected wizard could not be started. Plug-in io.github.abelgomez.asyncapi.ui was unable to load class io.github.abelgomez.asyncapi.ui.AsyncApiExecutableExtensionFactory. io.github.abelgomez.asyncapi.ui.AsyncApiExecutableExtensionFactory cannot be found by io.github.abelgomez.asyncapi.ui_0.6.1.qualifier

### ISSUE THREAD

**Issue by Aurora-Jerry** [SOM-Research/asyncapi-toolkit#5]
Excuse me，When I want to extract the file and add the plug-in to Eclipse, I can install it successfully, but I can't create the file, and I can't find the AsyncApiExecutableExtensionFactor. How can I solve this problem？

**Comment by Aurora-Jerry** [comment]
![image](https://user-images.githubusercontent.com/65485302/224998884-f1cde6e5-d3c5-42df-9af1-01bc69e2dbbc.png)

**Comment by abelgomez** [comment]
How are you installing the plug-ins? When you say that "you extract the file, and add the plug-in to Eclipse" makes me think you're installing the plug-in manually by simply copying the plug-ins to a local folder. Please, explain clearly the procedure you're following.

The plug-ins must be installed using the Update Site, if not, dependencies are not computed, and required plug-ins are not automatically installed.

If you're not able to install the plug-ins in an existing Eclipse installation, use the pre-packaged versions in the releases section https://github.com/SOM-Research/asyncapi-toolkit/releases

All the information about Installation Options can be found at: https://github.com/SOM-Research/asyncapi-toolkit/blob/master/doc/Installation.md

**Comment by Aurora-Jerry** [comment]
Thank you for your reply. I downloaded the latest source code from https://github.com/SOM-Research/asyncapi-toolkit/archive/refs/tags/v0.6.1.zip to my local and then extracted the files. I added it to Eclipse using update site by following the steps: help-install new software-add-name:Asyncapi,url-local:d:asyncapi-toolkit-master. Then I added the detected plugins and successfully installed them. However, when I tried to create an asyncapi project by selecting new-other-asyncapi-project, it prompted the error mentioned above. I couldn't find a way to solve this problem, so I'm asking for your help. As for why I only choose to do a local installation, it's because I may need to modify some parts of the program later, so I didn't directly use https://github.com/SOM-Research/asyncapi-toolkit/releases. I'm looking forward to your reply. Thank you!

**Comment by abelgomez** [comment]
I cannot understand how Eclipse has been able to detect anything installable from the sources ZIP, and to install the plug-ins. I'm afraid I'm missing some step or information. 

In any case: you cannot expect the plugins to work if installing from the sources. You have to install the plug-ins following any of the mentioned installation procedures (https://github.com/SOM-Research/asyncapi-toolkit/blob/master/doc/Installation.md). In all cases, you'll get a local installation. From your explanation (which, as I said, I don't completely understand), it is normal that you get a "class not found error", because you're not installing the *.class files, but the source java files. In any case, from what I've been able to understand, the installation procedure you're following is utterly wrong.

As a side note, if you need to modify the sources of the _AsyncAPI Toolkit_, you'll need a deep knowledge of how Eclipse and its plug-in environment works. I invite you to follow (if you have not done so) some of the following tutorials:

* https://www.vogella.com/tutorials/EclipsePlugin/article.html
* https://www.vogella.com/tutorials/EclipseTycho/article.html

You'll need to fully understand the concepts in the above tutorials to modify the tool available in this repository.

Since I'm afraid you're not following the standard installation procedure for any Eclipse plug-in, I'm closing this issue as "INVALID".
